### ISSUE TITLE
bug au niveau de l'ajout de liquidité

### ISSUE THREAD

**Issue by vavx** [ElrondNetwork/battleofyields#499]
bonjour,

j'ai voulu ajouter de la liquidité aux pools EGLD-MEX et EGLD-BUSD mais lors de la transaction, les jetons sont partis dans mon testnet wallet et depuis impossible de les retrouver dans le maiar-exchange. Je ne peux aussi plus voir les détails du wallet depuis maiar-exange.
Je suppose donc qu'ils devraient être sur le devnet wallet et non pas sur le testnet wallet.
Mon adresse: erd1de3m5tr9lqtpaedz3xr0p9uuvhrmql3trkth39l22jfkzmsw06eqsas3dl

![bug wallet](https://user-images.githubusercontent.com/90779495/133492661-0c77ce7d-456e-4a0f-b9db-11a42b3a40be.PNG)

![devnet 2](https://user-images.githubusercontent.com/90779495/133492665-019ad92b-7b9b-4f82-aa84-6f3bee2841ab.PNG)

![testnet](https://user-images.githubusercontent.com/90779495/133492667-ba043878-9bc9-48e1-a79a-902cdf8f853b.PNG)

**Comment by olagdev** [comment]
Make an effort, you have to do it in English and not in French.
Your tokens cannot change network. basic
